spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "4.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs - Version 4.0"
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
