spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "4.0"

loans:
  message: "Welcome to EazyBank loans related production APIs - version 4.0"
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
